title: 'Dalia Katan'
description: 'What might life look like if designed around curiosity?'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:


plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - vendor/bundle
  - assets/vendor/bundle
  - node_modules