title: 'Dalia Katan'
description: 'What might life look like if designed around curiosity?'
author: 'Dalia Katan'

sass:
  style: compressed

assets_path: '' 

collections:
  projects:
  for_you:
    output: true
    permalink: /for-you/:name/


plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - assets/vendor/bundle
  - vendor/bundle